### ISSUE TITLE
Temp variables cleared after "retrieve skin" effect

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [TlatoaniHJ/Tablisknu#2]
### Description
`retrieve skin` effect clears all temp variables set before, including function arguments

according to Nicofisi (from Sk Discord) this https://github.com/SkriptLang/Skript/commit/237b3dd928f3108d154204d3e98af1208e7679f4 might be related

### Steps to reproduce
```shell
command /test4:
    trigger:
        set {_test} to "hello"
        broadcast "<green>%{_test}%"
        retrieve skin of "Waltz" parsed as offline player with timeout 2 seconds into {_skin}
        broadcast "<light red>%{_test}%"
```
Output:
![default](https://user-images.githubusercontent.com/46863862/52866999-fc353180-3150-11e9-96f6-f4d47b610056.png)

**Comment by TlatoaniHJ** [comment]
Skript version?

**Comment by HAHAYOUDEAD** [comment]
2.3.5, latest Paper

**Comment by TlatoaniHJ** [comment]
If you can contact me in Discord, I can send you a version that should fix this issue.

**Comment by TlatoaniHJ** [comment]
(Issue resolved in Discord)
