### ISSUE TITLE
Tablisknu bug - Messing with org.bukkit.inventory.ShapedRecipe

### ISSUE THREAD

**Issue by aescraftbr** [TlatoaniHJ/Tablisknu#4]
Ok, so I was checking shanebees snippets, and I found one that creates custom recipes.
you can see the conversation here: https://forums.skunity.com/threads/recipe-manager-1-13-2-only.8653/

tl;dr: When using tablisknu, it breaks the recipe convertion to boolean.

```27.08 04:18:53 [Server] Server thread/WARN method ShapedRecipe#shape called with (123 (String), 456 (String), 789 (String)) returned shaped recipe (ShapedRecipe), which could not be converted to Boolean```

When I remove tablisknu from my server, this error disappears. 
Thanks.

**Comment by TlatoaniHJ** [comment]
MC, Skript, Tablisknu, ProtocolLib versions?

**Comment by TlatoaniHJ** [comment]
Please also include the code you used.

**Comment by aescraftbr** [comment]
- MC 1.14.4 - Craftbukkit ver git-spigot-ea7e48b-368f4e9 (mc 1.14.4) ver 1.14.4-R0.1 Snapshot.
- Skript version 2.4-beta5
- skript-mirror version 2.0.0-SNAPSHOT
- Tablisknu version 1.0-BETA.9
- ProtocolLib version 4.5.0-SNAPSHOT

CODE:

```
import:
  org.bukkit.Bukkit
  org.bukkit.inventory.ShapedRecipe
  org.bukkit.inventory.RecipeChoice$ExactChoice
  org.bukkit.NamespacedKey
 
#! Register shaped recipe with custom ingredients !#
effect register [new] shaped recipe for %item% using %items% with id %string%:
  trigger:
    set {_ing::*} to expressions-2
    loop 9 times:
      if {_ing::%loop-number%} is not set:
        set {_ing::%loop-number%} to air
    #! ID + NamespacedKey !#
    set {_id} to expression-3
    replace all " " with "_" in {_id}
    set {_key} to new NamespacedKey(Bukkit.getPluginManager().getPlugin("Skript"), {_id})
    #! Create Recipe !#
    set {_recipe} to new ShapedRecipe({_key}, expression-1)
    loop 9 times:
      set {_choices::%loop-number%} to new ExactChoice({_ing::%loop-number%})
    #! Ingredients !#
    {_recipe}.shape("123","456","789")
    loop {_ing::*}:
      {_recipe}.setIngredient(loop-index, {_choices::%loop-index%})
    Bukkit.addRecipe({_recipe})
 
#! Unlock a recipe for a player !#
effect [(1¦un)]discover recipe %string% for %players%:
  trigger:
    set {_string} to expression-1
    replace all " " with "_" in {_string}
    set {_key} to new NamespacedKey(Bukkit.getPluginManager().getPlugin("Skript"), {_string})
    loop expressions-2:
      if parse mark is 1:
        loop-expression.undiscoverRecipe({_key})
      else:
        loop-expression.discoverRecipe({_key})
 
on join:
  discover recipe "jukebox" for player
 
on skript load:
  set {_nbt} to "{SkullOwner:{Id:""04049c90-d3e9-4621-9caf-000000aaa218"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGQxZDhjNTA0ODY3OTMzNzAzZGEzNmVjMTFmNTM4ZjYyNjVmOTg0NDFkODgxZWFjNDhlZjJjNDkzNGMxYiJ9fX0=""}]}},display:{Lore:['{""text"":""§aToca-Discos""}'],Name:'{""text"":""§9Jukebox""}'},Damage:3}"
  set {_item} to player head
  set nbt of {_item} to {_nbt}
  set {_nbt} to "{HideFlags:47,display:{Lore:['{""text"":""§eTítulo - 64x §6AesCoins""}'],Name:'{""text"":""§6AesCheque""}'},Enchantments:[{lvl:1s,id:""minecraft:unbreaking""}]}"
  set {_ing} to paper
  set nbt of {_ing} to {_nbt}
  register new shaped recipe for {_item} using oak plank, oak plank, oak plank, oak plank, {_ing}, oak plank, oak plank, oak plank and oak plank with id "jukebox"
```

Error:

```
27.08 03:26:17 [Server] Server thread/WARN method ShapedRecipe#shape called with (123 (String), 456 (String), 789 (String)) returned shaped recipe (ShapedRecipe), which could not be converted to Boolean
```

**Comment by TlatoaniHJ** [comment]
Does this have effects pther than printing the error to console?

**Comment by TlatoaniHJ** [comment]
Can you identify the specific line of code that causes the error to appear?

**Comment by aescraftbr** [comment]
> Does this have effects pther than printing the error to console?

Yes, this doesn't allow to register the new recipe. You can't use the recipe, as it is not registered.

The thing is, for shanebee, this works. Then, to pinpoint where the issue was coming from, I removed all addons from skript.

Then, I restarted the server only with Skript + Skript-mirror + Sknbeet. The skript worked flawless.
Then, I started adding one addon at a time, until I found out what addon was causing the issue.
And this addon is Tablisknu.
When I add tablisknu, restart the server, the error happens. Without tablisknu, no error, and the skript works (registering the recipe)

> Can you identify the specific line of code that causes the error to appear?

I don't know what line causes it, my guess as it's a error related to "org.bukkit.inventory.ShapedRecipe", that this lines get messed up with tablisknu:

```
    #! Create Recipe !#
    set {_recipe} to new ShapedRecipe({_key}, expression-1)
    loop 9 times:
      set {_choices::%loop-number%} to new ExactChoice({_ing::%loop-number%})
```

Thanks!

**Comment by TlatoaniHJ** [comment]
Download the version of Tablisknu at this link (tlatoani.us/tablisknu/download/snapshot) and see if it fixes the issue.

**Comment by aescraftbr** [comment]
Yep. Fixed.
