### ISSUE TITLE
Latter is not a text type

### ISSUE THREAD

**Issue by iWanheda** [TlatoaniHJ/Tablisknu#5]
`{_p}'s nametag can't be set to '"potter" for all players' because the latter is not a text (hcf.sk, line 114: set {_p}'s nametag to "potter" for all players')`

Even if I do %all players% or loop-player, anything, even setting "SkymeR_" as the `for` player it still won't work

**Comment by TlatoaniHJ** [comment]
`for all players` needs to come before `set to "potter"`, so it would be `set {_p}'s nametag for all players to "potter"`.

**Comment by TlatoaniHJ** [comment]
Note that unless you have a very weird use case you should probably just be doing `set {_p}'s nametag to "potter"`; specifying `for all players` would only set the nametag for players that are currently online, but leave the player's default nametag unchanged, so players that join after the effect is executed would see the previous nametag.

**Comment by iWanheda** [comment]
Hey, that was an example, what if I want to set it to a loop-player?

**Comment by TlatoaniHJ** [comment]
Yes, in that case you would do like I said, `set {_p}'s nametag for loop-player to "potter"`

**Comment by iWanheda** [comment]
Thank you so much! Helpful mate, may I add you on Discord?

**Comment by TlatoaniHJ** [comment]
Sure, my username is Tlatoani.

**Comment by iWanheda** [comment]
Hey, I need your #IDID

Anyways, any way to set suffix?
https://b.catgirlsare.sexy/QXgj.png

**Comment by TlatoaniHJ** [comment]
Tlatoani#4018. Tablisknu doesn't have nametag prefix/suffixes right now. It looks like this issue is fixed so I'll close this issue. For any later problems you can open a new issue and for other questions you can contact me on Discord.
